on:
  workflow_dispatch:
  schedule:
    - cron: "37 * * * *"

jobs:
  getActive:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"

      - name: Append new data to the json files
        run: go run .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update